#!/bin/bash
# Autonomous-drive smoke test across every CARLA town.
# For each town: full bring-up (run_localization_demo.sh), one gateway `drive`,
# then judge: did the ego reach AUTONOMOUS and actually move?
# Results: docs/town_test_results.md  (+ raw logs /tmp/towntest_*)
set -u
REPO="$(cd "$(dirname "$0")/.." && pwd)"
SUDO() { echo 1 | sudo -S "$@"; }
OUT="$REPO/docs/town_test_results.md"
TOWNS=${1:-"Town01 Town02 Town03 Town04 Town05 Town06 Town07 Town10HD"}

{
  echo "# CARLA all-town autonomous-drive test"
  echo ""
  echo "Generated by scripts/test_all_towns.sh — one bring-up + one \`drive\` per town."
  echo ""
  echo "| Town | Localized | Route | Trajectory | Autonomous | Max km/h | Moved m | Verdict |"
  echo "|---|---|---|---|---|---|---|---|"
} > "$OUT"

for TOWN in $TOWNS; do
  echo "=== [$TOWN] bring-up ==="
  bash "$REPO/scripts/run_localization_demo.sh" "$TOWN" > "/tmp/towntest_${TOWN}_up.log" 2>&1
  LOC=$(grep -c 'Translation' "/tmp/towntest_${TOWN}_up.log" || true)
  sleep 5
  echo "=== [$TOWN] drive ==="
  SUDO docker exec autoware bash -lc \
    "export FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/udp.xml; source /opt/autoware/setup.bash; \
     python3 /root/drive_monitor.py drive" > "/tmp/towntest_${TOWN}_drive.log" 2>&1 || true

  python3 - "$TOWN" "$LOC" "/tmp/towntest_${TOWN}_drive.log" "$OUT" <<'PY'
import re, sys, math
town, loc, log, out = sys.argv[1], sys.argv[2] != "0", sys.argv[3], sys.argv[4]
txt = open(log, errors="ignore").read()
rows = re.findall(r"route=(\w+) traj=(\d+) mode=(\w+) .*?spd=([\d.]+)km/h ego=\((-?[\d.]+),(-?[\d.]+)\)", txt)
route = any(r[0] == "SET" for r in rows)
traj = max((int(r[1]) for r in rows), default=0)
auto = any(r[2] == "AUTONOMOUS" for r in rows)
spd = max((float(r[3]) for r in rows), default=0.0)
pts = [(float(r[4]), float(r[5])) for r in rows]
moved = 0.0
if len(pts) > 1:
    moved = math.hypot(pts[-1][0] - pts[0][0], pts[-1][1] - pts[0][1])
verdict = "✅ PASS" if (auto and spd > 5 and moved > 10) else ("⚠️ partial" if route else "❌ FAIL")
with open(out, "a") as f:
    f.write(f"| {town} | {'✅' if loc else '❌'} | {'SET' if route else 'UNSET'} | {traj} | "
            f"{'✅' if auto else '❌'} | {spd:.1f} | {moved:.0f} | {verdict} |\n")
print(f"[{town}] auto={auto} spd={spd:.1f} moved={moved:.0f} -> {verdict}")
PY
done

echo "" >> "$OUT"
echo "Raw logs: /tmp/towntest_<town>_{up,drive}.log" >> "$OUT"
echo "=== DONE — results in $OUT ==="
cat "$OUT"
